### PR TITLE
Making NoPE Proxy work with Burp 2.1+

### PR DESCRIPTION
**Pull request by jfish7**

### CODE REVIEW

**Comment by jfish7** [comment]
If you want to build the jar locally, run `mvn clean compile assembly::single`. It's stored at `Burp-Non-HTTP-Extension/NonHTTPProxy/target/NonHTTPProxy-0.0.1-SNAPSHOT-jar-with-dependencies.jar`

**Comment by jfish7** [comment]
If you're curious why it didn't work with Burp 2.1+, it's because NoPE proxy relies on Hibernate, which relies on JAXB, which is no longer supported in the runtime of Java 9+. In order to fix it, I removed the dependency of JAXB by creating the session factory in `HibHelper.java` instead of relying on Hibernate to parse the `hibernate.cfg.xml`.

**Comment by summitt** [comment]
Thanks @jfish7 for making this change! I'm merging the changes creating a new release.

**Comment by jfish7** [comment]
Thank you @summitt! However, I believe my changes did break some other functionality in the tool, since my main use case was around the DSN listener and the TCP proxy. I'll put in some time this month to ensure the other functionality works with my changes.

**Pull request merged**
